In [13]:
import pandas as pd

df_users = pd.read_csv("./data/clean/clean_users.csv", encoding="utf-8-sig")
df_products = pd.read_csv("./data/clean/clean_products.csv", encoding="utf-8-sig")
df_browses = pd.read_csv("./data/clean/clean_browses.csv", encoding="utf-8-sig")
df_orders = pd.read_csv("./data/clean/clean_orders.csv", encoding="utf-8-sig")
print("✅ 清洗数据读取完成！")

✅ 清洗数据读取完成！

In [14]:
# 订单表时间处理
df_orders["created_at"] = pd.to_datetime(df_orders["created_at"])
df_orders["order_hour"] = df_orders["created_at"].dt.hour   # 小时特征
df_orders["order_month"] = df_orders["created_at"].dt.month # 月份特征

# 浏览表时间处理
df_browses["created_at"] = pd.to_datetime(df_browses["created_at"])
df_browses["browse_hour"] = df_browses["created_at"].dt.hour

print("✅ 时间特征衍生完成！")

✅ 时间特征衍生完成！

In [15]:
# 1. 先删掉 orders 和 products 合并后多余的 id 列
df_merge1 = pd.merge(df_orders, df_products, 
                     left_on="product_id", right_on="id", how="left")
# 删掉来自 products 的 id_y（已用 product_id 关联），
# 以及来自 orders 的 id_x（已作为 order_id 用途）
df_merge1 = df_merge1.drop(columns=["id_x", "id_y", "status_y"])  # status_y 同理可删

# 2. 关联 users 表，删掉多余的 id
df_merge2 = pd.merge(df_merge1, df_users, 
                     left_on="user_id", right_on="id", how="left")
df_merge2 = df_merge2.drop(columns=["id"])  # 删掉来自 users 的 id

# 3. 关联 browses 表，删掉多余的 id
df_full = pd.merge(df_merge2, df_browses,
                   on=["user_id", "product_id"], how="left")
df_full = df_full.drop(columns=["id"])  # 删掉来自 browses 的 id

print(f"融合后宽表数据维度：{df_full.shape}")
print("宽表字段预览：")
print(df_full.columns.tolist())

融合后宽表数据维度：(1000012, 28)
宽表字段预览：
['user_id', 'product_id', 'quantity', 'total_amount', 'status_x', 'created_at_x', 'order_hour', 'order_month', 'name', 'category_id', 'category_path', 'price', 'original_price', 'stock', 'sales', 'views', 'favorites', 'tags_x', 'nickname', 'gender', 'age', 'city', 'register_time', 'tags_y', 'duration', 'action', 'created_at_y', 'browse_hour']

In [33]:
# 1. 先删掉 orders 和 products 合并后多余的 id 列
df_merge1 = pd.merge(df_orders, df_products, 
                     left_on="product_id", right_on="id", how="left")
# 删掉来自 products 的 id_y（已用 product_id 关联），
# 以及来自 orders 的 id_x（已作为 order_id 用途）
df_merge1 = df_merge1.drop(columns=["id_x", "id_y", "status_y"])  # status_y 同理可删

# 2. 关联 users 表，删掉多余的 id
df_merge2 = pd.merge(df_merge1, df_users, 
                     left_on="user_id", right_on="id", how="left")
df_merge2 = df_merge2.drop(columns=["id"])  # 删掉来自 users 的 id

# 3. 关联 browses 表，删掉多余的 id
df_half = pd.merge(df_merge2, df_browses,
                   on=["user_id", "product_id"], how="left")
df_half = df_half.drop(columns=["id"])  # 删掉来自 browses 的 id

print(f"融合后宽表数据维度：{df_full.shape}")
print("宽表字段预览：")
print(df_half.columns.tolist())

融合后宽表数据维度：(2431, 28)
宽表字段预览：
['user_id', 'product_id', 'quantity', 'total_amount', 'status_x', 'created_at_x', 'order_hour', 'order_month', 'name', 'category_id', 'category_path', 'price', 'original_price', 'stock', 'sales', 'views', 'favorites', 'tags_x', 'nickname', 'gender', 'age', 'city', 'register_time', 'tags_y', 'duration', 'action', 'created_at_y', 'browse_hour']

In [34]:
df_half.to_csv("./data/feature/half_feature_data.csv", index=False, encoding="utf-8-sig")
print("✅ 全维度特征宽表已保存至data/feature目录！")
df_half.head()

✅ 全维度特征宽表已保存至data/feature目录！

,user_id,product_id,quantity,total_amount,status_x,created_at_x,order_hour,order_month,name,category_id,...,nickname,gender,age,city,register_time,tags_y,duration,action,created_at_y,browse_hour
0,10704,21850,2,0,3,2026-04-07 02:26:14,2,4,伊利 速冻水饺,62.0,...,张佳,2,31,南宁,2024-12-05 20:45:06,"时尚达人,白领精英,夜猫子",NaN,NaN,NaT,NaN
1,12846,45460,1,0,3,2025-08-27 17:51:34,17,8,阿迪达斯 外套,43.0,...,李欣,1,30,深圳,2025-06-04 08:37:23,"数码发烧友,白领精英,新品爱好者",NaN,NaN,NaT,NaN
2,18510,2074,1,0,3,2025-04-11 23:34:51,23,4,雅诗兰黛 眼霜 标准版,55.0,...,梁建华,1,34,武汉,2025-08-31 12:56:21,"数码发烧友,宝妈宝爸",NaN,NaN,NaT,NaN
3,48961,529,2,0,3,2025-10-23 01:08:51,1,10,OPPO 充电器,11.0,...,程金凤,2,64,重庆,2025-06-13 00:36:09,"退休人士,时尚达人,数码发烧友,自由职业,周末购物",NaN,NaN,NaT,NaN
4,971,29946,1,0,2,2025-06-25 05:41:26,5,6,格力 微波炉,31.0,...,何华,1,33,南宁,2025-10-22 01:08:23,"数码发烧友,白领精英,居家生活,囤货党,时尚达人",NaN,NaN,NaT,NaN

In [35]:
df_full=pd.read_csv("./data/feature/full_feature_data.csv", encoding="utf-8-sig")
df_full.head()

,user_id,product_id,quantity,total_amount,status_x,created_at_x,order_hour,order_month,name,category_id,...,nickname,gender,age,city,register_time,tags_y,duration,action,created_at_y,browse_hour
0,3094,7999,1,0,2,2026-04-02 03:05:08,3,4,格力 电视,32.0,...,龙丽娟,1,23,宁波,2024-11-24 14:45:24,"学生党,新品爱好者",6.0,1.0,2025-10-15 21:57:15,21.0
1,18933,2621,1,0,3,2025-08-21 23:25:46,23,8,顾家 四件套,73.0,...,陈凤兰,2,49,青岛,2024-06-25 08:04:12,"时尚达人,理性对比",42.0,1.0,2025-08-09 21:53:03,21.0
2,9649,2413,2,0,3,2025-12-05 21:44:49,21,12,苹果 U盘,22.0,...,李云,2,48,无锡,2024-12-02 20:08:39,"宝妈宝爸,学生党",119.0,4.0,2025-10-23 09:11:48,9.0
3,22563,5268,1,0,3,2025-01-20 14:58:10,14,1,湾仔码头 咖啡 2025款,63.0,...,李丽,2,45,深圳,2024-08-05 18:55:40,"品质追求,冲动消费,理性对比",19.0,1.0,2025-11-07 22:23:24,22.0
4,3311,6495,5,0,3,2026-03-07 01:45:21,1,3,小米 微波炉,32.0,...,詹琴,2,23,沈阳,2024-12-05 11:33:23,"学生党,白领精英",52.0,1.0,2025-07-12 08:44:58,8.0